version: '3'
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 8083:80
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=http://www.frozens.vip
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=61ae7978d59e85f964f9
      - DRONE_GITHUB_CLIENT_SECRET=a8519a1a1f015a9a9c24c715161cea0f580c6e47
      - DRONE_DEBUG=true
      - DRONE_GITHUB=true
      - DRONE_PROVIDER=github
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
  drone-agent:
    image: drone/agent:latest
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_SERVER=http://www.frozens.vip
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_DEBUG=true
      - DOCKER_HOST=tcp://docker-bind:2375
  docker-bind:
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay
