// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver" json:"ver,omitempty"`
	Opr                  int32    `protobuf:"varint,2,opt,name=opr" json:"opr,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Toid                 int32    `protobuf:"varint,4,opt,name=toid" json:"toid,omitempty"`
	Body                 []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_ca0a78bbc38045b9, []int{0}
}
func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (dst *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(dst, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOpr() int32 {
	if m != nil {
		return m.Opr
	}
	return 0
}

func (m *Proto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Proto) GetToid() int32 {
	if m != nil {
		return m.Toid
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PushMsgReq struct {
	Key                  int32    `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_ca0a78bbc38045b9, []int{1}
}
func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (dst *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(dst, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *PushMsgReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_ca0a78bbc38045b9, []int{2}
}
func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (dst *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(dst, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Proto)(nil), "grpc.Proto")
	proto.RegisterType((*PushMsgReq)(nil), "grpc.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "grpc.PushMsgReply")
}

func init() { proto.RegisterFile("im.proto", fileDescriptor_im_ca0a78bbc38045b9) }

var fileDescriptor_im_ca0a78bbc38045b9 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x4f, 0x6b, 0x85, 0x30,
	0x10, 0xc4, 0xab, 0xcf, 0xf4, 0xcf, 0xbe, 0xc7, 0x43, 0xf6, 0x14, 0x7a, 0xb2, 0x39, 0x79, 0x12,
	0x6a, 0xef, 0x85, 0x1e, 0x8b, 0x08, 0x92, 0x7e, 0x03, 0x4d, 0xb0, 0x01, 0x4b, 0xd2, 0x68, 0x85,
	0x7c, 0xfb, 0x92, 0xd5, 0x7a, 0xe8, 0x6d, 0xf6, 0x37, 0xec, 0xcc, 0xc0, 0xbd, 0xf9, 0xaa, 0x9c,
	0xb7, 0x8b, 0xc5, 0x6c, 0xf4, 0x6e, 0x10, 0x03, 0xb0, 0x8e, 0xce, 0x1c, 0x4e, 0xab, 0xf6, 0x3c,
	0x29, 0x92, 0x92, 0xc9, 0x28, 0x23, 0xb1, 0xce, 0xf3, 0x74, 0x23, 0xd6, 0x79, 0xbc, 0x42, 0x6a,
	0x14, 0x3f, 0x11, 0x48, 0x8d, 0x42, 0x84, 0x6c, 0xb1, 0x46, 0xf1, 0x8c, 0x08, 0xe9, 0xc8, 0x7a,
	0xab, 0x02, 0x67, 0x45, 0x52, 0x5e, 0x24, 0x69, 0xf1, 0x06, 0xd0, 0xfd, 0xcc, 0x9f, 0xed, 0x3c,
	0x4a, 0xfd, 0x1d, 0x73, 0x1b, 0x1d, 0xfe, 0x9a, 0x1a, 0x1d, 0xf0, 0x09, 0x18, 0x6d, 0xa2, 0xae,
	0x73, 0x7d, 0xae, 0xe2, 0xb4, 0x8a, 0x76, 0xc9, 0xcd, 0x11, 0x57, 0xb8, 0x1c, 0x11, 0x6e, 0x0a,
	0xf5, 0x2b, 0x3c, 0xbc, 0xb7, 0x1f, 0xda, 0xaf, 0x66, 0xd0, 0xf8, 0x0c, 0x77, 0xbb, 0x89, 0xf9,
	0xfe, 0x7b, 0xd4, 0x3d, 0xe2, 0x3f, 0xe2, 0xa6, 0x20, 0x6e, 0xfa, 0x5b, 0x8a, 0x7d, 0xf9, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x7a, 0x99, 0xcc, 0xb7, 0x10, 0x01, 0x00, 0x00,
}
