// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReceiveReq struct {
	Proto                *Proto   `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveReq) Reset()         { *m = ReceiveReq{} }
func (m *ReceiveReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveReq) ProtoMessage()    {}
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_3bef0653abf459a4, []int{0}
}
func (m *ReceiveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReq.Unmarshal(m, b)
}
func (m *ReceiveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReq.Marshal(b, m, deterministic)
}
func (dst *ReceiveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReq.Merge(dst, src)
}
func (m *ReceiveReq) XXX_Size() int {
	return xxx_messageInfo_ReceiveReq.Size(m)
}
func (m *ReceiveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReq proto.InternalMessageInfo

func (m *ReceiveReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type ReceiveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveReply) Reset()         { *m = ReceiveReply{} }
func (m *ReceiveReply) String() string { return proto.CompactTextString(m) }
func (*ReceiveReply) ProtoMessage()    {}
func (*ReceiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_3bef0653abf459a4, []int{1}
}
func (m *ReceiveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReply.Unmarshal(m, b)
}
func (m *ReceiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReply.Marshal(b, m, deterministic)
}
func (dst *ReceiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReply.Merge(dst, src)
}
func (m *ReceiveReply) XXX_Size() int {
	return xxx_messageInfo_ReceiveReply.Size(m)
}
func (m *ReceiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReply proto.InternalMessageInfo

type CheckReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReq) Reset()         { *m = CheckReq{} }
func (m *CheckReq) String() string { return proto.CompactTextString(m) }
func (*CheckReq) ProtoMessage()    {}
func (*CheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_3bef0653abf459a4, []int{2}
}
func (m *CheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReq.Unmarshal(m, b)
}
func (m *CheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReq.Marshal(b, m, deterministic)
}
func (dst *CheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReq.Merge(dst, src)
}
func (m *CheckReq) XXX_Size() int {
	return xxx_messageInfo_CheckReq.Size(m)
}
func (m *CheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReq proto.InternalMessageInfo

func (m *CheckReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CheckReply struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReply) Reset()         { *m = CheckReply{} }
func (m *CheckReply) String() string { return proto.CompactTextString(m) }
func (*CheckReply) ProtoMessage()    {}
func (*CheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_3bef0653abf459a4, []int{3}
}
func (m *CheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReply.Unmarshal(m, b)
}
func (m *CheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReply.Marshal(b, m, deterministic)
}
func (dst *CheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReply.Merge(dst, src)
}
func (m *CheckReply) XXX_Size() int {
	return xxx_messageInfo_CheckReply.Size(m)
}
func (m *CheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReply proto.InternalMessageInfo

func (m *CheckReply) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func init() {
	proto.RegisterType((*ReceiveReq)(nil), "grpc.ReceiveReq")
	proto.RegisterType((*ReceiveReply)(nil), "grpc.ReceiveReply")
	proto.RegisterType((*CheckReq)(nil), "grpc.CheckReq")
	proto.RegisterType((*CheckReply)(nil), "grpc.CheckReply")
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor_logic_3bef0653abf459a4) }

var fileDescriptor_logic_3bef0653abf459a4 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0xd3, 0xb2, 0x64, 0x14, 0x91, 0x39, 0xc5, 0x1e, 0xa2, 0xf6, 0x14, 0x04, 0x46, 0xf6,
	0x08, 0x5d, 0x3b, 0xc4, 0xf6, 0x06, 0xad, 0x83, 0x2d, 0x5a, 0x6e, 0x12, 0x82, 0x6f, 0x1f, 0xbb,
	0x6e, 0x45, 0xdd, 0x76, 0xfe, 0x6f, 0xbe, 0x9d, 0x19, 0x88, 0xea, 0xa6, 0x54, 0x32, 0xd3, 0x6d,
	0xf3, 0x6c, 0x70, 0x52, 0xb6, 0x5a, 0xb2, 0x50, 0xdd, 0x86, 0x9a, 0x6f, 0x01, 0x04, 0x49, 0x52,
	0x1d, 0x09, 0x7a, 0xe0, 0x0a, 0x02, 0x1b, 0xcf, 0xbd, 0xa5, 0xb7, 0x8e, 0xf2, 0x28, 0x33, 0xdd,
	0xd9, 0xc9, 0x44, 0x62, 0x20, 0x3c, 0x81, 0xf8, 0x23, 0xe8, 0xba, 0xe7, 0x0c, 0xc2, 0xc3, 0x95,
	0x64, 0x65, 0xf4, 0x04, 0x7c, 0x55, 0x58, 0x37, 0x10, 0xbe, 0x2a, 0xf8, 0x02, 0xc0, 0x31, 0x5d,
	0xf7, 0x98, 0xc2, 0xb8, 0xa2, 0xde, 0x61, 0xf3, 0xcc, 0xef, 0x10, 0x1f, 0xcd, 0x6e, 0x67, 0x6a,
	0x3b, 0x25, 0x09, 0x37, 0x10, 0xd8, 0x7e, 0x4c, 0x86, 0xc1, 0xef, 0x8f, 0x59, 0xfa, 0x53, 0x9b,
	0xb1, 0x23, 0xdc, 0xc1, 0xcc, 0x2d, 0x82, 0x0e, 0x7f, 0x0f, 0x61, 0xf8, 0x97, 0x58, 0xe5, 0x32,
	0xb5, 0x27, 0xec, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0x5d, 0xb7, 0x83, 0x12, 0x01, 0x00,
	0x00,
}
