// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: im.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for IMService service

type IMService interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...client.CallOption) (*PushMsgReply, error)
}

type iMService struct {
	c    client.Client
	name string
}

func NewIMService(name string, c client.Client) IMService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &iMService{
		c:    c,
		name: name,
	}
}

func (c *iMService) PushMsg(ctx context.Context, in *PushMsgReq, opts ...client.CallOption) (*PushMsgReply, error) {
	req := c.c.NewRequest(c.name, "IMService.PushMsg", in)
	out := new(PushMsgReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IMService service

type IMServiceHandler interface {
	PushMsg(context.Context, *PushMsgReq, *PushMsgReply) error
}

func RegisterIMServiceHandler(s server.Server, hdlr IMServiceHandler, opts ...server.HandlerOption) error {
	type iMService interface {
		PushMsg(ctx context.Context, in *PushMsgReq, out *PushMsgReply) error
	}
	type IMService struct {
		iMService
	}
	h := &iMServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&IMService{h}, opts...))
}

type iMServiceHandler struct {
	IMServiceHandler
}

func (h *iMServiceHandler) PushMsg(ctx context.Context, in *PushMsgReq, out *PushMsgReply) error {
	return h.IMServiceHandler.PushMsg(ctx, in, out)
}
