// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/proto/im.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{0}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PingRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRes) Reset()         { *m = PingRes{} }
func (m *PingRes) String() string { return proto.CompactTextString(m) }
func (*PingRes) ProtoMessage()    {}
func (*PingRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{1}
}
func (m *PingRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRes.Unmarshal(m, b)
}
func (m *PingRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRes.Marshal(b, m, deterministic)
}
func (dst *PingRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRes.Merge(dst, src)
}
func (m *PingRes) XXX_Size() int {
	return xxx_messageInfo_PingRes.Size(m)
}
func (m *PingRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRes.DiscardUnknown(m)
}

var xxx_messageInfo_PingRes proto.InternalMessageInfo

func (m *PingRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PushMsgReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{2}
}
func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (dst *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(dst, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PushMsgReq) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *PushMsgReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PushMsgRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgRes) Reset()         { *m = PushMsgRes{} }
func (m *PushMsgRes) String() string { return proto.CompactTextString(m) }
func (*PushMsgRes) ProtoMessage()    {}
func (*PushMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{3}
}
func (m *PushMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgRes.Unmarshal(m, b)
}
func (m *PushMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgRes.Marshal(b, m, deterministic)
}
func (dst *PushMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgRes.Merge(dst, src)
}
func (m *PushMsgRes) XXX_Size() int {
	return xxx_messageInfo_PushMsgRes.Size(m)
}
func (m *PushMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgRes proto.InternalMessageInfo

func (m *PushMsgRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PushMsgsReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgsReq) Reset()         { *m = PushMsgsReq{} }
func (m *PushMsgsReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgsReq) ProtoMessage()    {}
func (*PushMsgsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{4}
}
func (m *PushMsgsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgsReq.Unmarshal(m, b)
}
func (m *PushMsgsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgsReq.Marshal(b, m, deterministic)
}
func (dst *PushMsgsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgsReq.Merge(dst, src)
}
func (m *PushMsgsReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgsReq.Size(m)
}
func (m *PushMsgsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgsReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgsReq proto.InternalMessageInfo

func (m *PushMsgsReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PushMsgsReq) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *PushMsgsReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PushMsgsRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgsRes) Reset()         { *m = PushMsgsRes{} }
func (m *PushMsgsRes) String() string { return proto.CompactTextString(m) }
func (*PushMsgsRes) ProtoMessage()    {}
func (*PushMsgsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_92783b750eca4a27, []int{5}
}
func (m *PushMsgsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgsRes.Unmarshal(m, b)
}
func (m *PushMsgsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgsRes.Marshal(b, m, deterministic)
}
func (dst *PushMsgsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgsRes.Merge(dst, src)
}
func (m *PushMsgsRes) XXX_Size() int {
	return xxx_messageInfo_PushMsgsRes.Size(m)
}
func (m *PushMsgsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgsRes.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgsRes proto.InternalMessageInfo

func (m *PushMsgsRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*PingReq)(nil), "proto.PingReq")
	proto.RegisterType((*PingRes)(nil), "proto.PingRes")
	proto.RegisterType((*PushMsgReq)(nil), "proto.PushMsgReq")
	proto.RegisterType((*PushMsgRes)(nil), "proto.PushMsgRes")
	proto.RegisterType((*PushMsgsReq)(nil), "proto.PushMsgsReq")
	proto.RegisterType((*PushMsgsRes)(nil), "proto.PushMsgsRes")
}

func init() { proto.RegisterFile("rpc/proto/im.proto", fileDescriptor_im_92783b750eca4a27) }

var fileDescriptor_im_92783b750eca4a27 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2a, 0x48, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xcc, 0xd5, 0x03, 0x33, 0x84, 0x58, 0xc1, 0x94, 0x92,
	0x24, 0x17, 0x7b, 0x40, 0x66, 0x5e, 0x7a, 0x50, 0x6a, 0xa1, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x22, 0x4c, 0xaa, 0x58, 0x48,
	0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x18, 0x2c, 0xcd, 0x11, 0x04, 0xe5, 0x29, 0x39,
	0x70, 0x71, 0x05, 0x94, 0x16, 0x67, 0xf8, 0x16, 0x63, 0x33, 0x40, 0x48, 0x80, 0x8b, 0xb9, 0x38,
	0x33, 0x45, 0x82, 0x09, 0x2c, 0x00, 0x62, 0x82, 0x44, 0x72, 0x8b, 0xd3, 0x25, 0x98, 0x15, 0x18,
	0x35, 0x78, 0x82, 0x40, 0x4c, 0x25, 0x15, 0x24, 0x13, 0x70, 0xdb, 0xe3, 0xc8, 0xc5, 0x0d, 0x55,
	0x55, 0x4c, 0xae, 0x45, 0xaa, 0xc8, 0x46, 0xe0, 0xb4, 0xc9, 0x68, 0x1e, 0x23, 0x17, 0xa7, 0xa7,
	0x6f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x06, 0x17, 0x0b, 0x28, 0x08, 0x84, 0xf8,
	0x20, 0x81, 0xa6, 0x07, 0x0d, 0x2a, 0x29, 0x54, 0x7e, 0xb1, 0x12, 0x83, 0x90, 0x21, 0x17, 0x3b,
	0xd4, 0x78, 0x21, 0x41, 0x98, 0x24, 0x3c, 0x64, 0xa4, 0x30, 0x84, 0x40, 0x5a, 0x4c, 0xb8, 0x38,
	0x60, 0x2e, 0x12, 0x12, 0x42, 0x55, 0x00, 0xf2, 0xa5, 0x14, 0xa6, 0x58, 0xb1, 0x12, 0x43, 0x12,
	0x1b, 0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x9f, 0x75, 0x8c, 0xd4, 0x01, 0x00,
	0x00,
}
