// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckUserReq struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserReq) Reset()         { *m = CheckUserReq{} }
func (m *CheckUserReq) String() string { return proto.CompactTextString(m) }
func (*CheckUserReq) ProtoMessage()    {}
func (*CheckUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b4317bf0ba0734de, []int{0}
}
func (m *CheckUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserReq.Unmarshal(m, b)
}
func (m *CheckUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserReq.Marshal(b, m, deterministic)
}
func (dst *CheckUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserReq.Merge(dst, src)
}
func (m *CheckUserReq) XXX_Size() int {
	return xxx_messageInfo_CheckUserReq.Size(m)
}
func (m *CheckUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserReq proto.InternalMessageInfo

func (m *CheckUserReq) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type CheckUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserRes) Reset()         { *m = CheckUserRes{} }
func (m *CheckUserRes) String() string { return proto.CompactTextString(m) }
func (*CheckUserRes) ProtoMessage()    {}
func (*CheckUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b4317bf0ba0734de, []int{1}
}
func (m *CheckUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserRes.Unmarshal(m, b)
}
func (m *CheckUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserRes.Marshal(b, m, deterministic)
}
func (dst *CheckUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserRes.Merge(dst, src)
}
func (m *CheckUserRes) XXX_Size() int {
	return xxx_messageInfo_CheckUserRes.Size(m)
}
func (m *CheckUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserRes proto.InternalMessageInfo

func (m *CheckUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b4317bf0ba0734de, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckUserReq)(nil), "proto.CheckUserReq")
	proto.RegisterType((*CheckUserRes)(nil), "proto.CheckUserRes")
	proto.RegisterType((*User)(nil), "proto.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_b4317bf0ba0734de) }

var fileDescriptor_user_b4317bf0ba0734de = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4a, 0x5c, 0x3c, 0xce, 0x19,
	0xa9, 0xc9, 0xd9, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0x99, 0x79,
	0x69, 0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x3e, 0x8a, 0x9a, 0x62,
	0x21, 0x79, 0x2e, 0x16, 0x90, 0x41, 0x60, 0x35, 0xdc, 0x46, 0xdc, 0x10, 0x03, 0xf5, 0xc0, 0xb2,
	0x60, 0x09, 0x25, 0x31, 0x2e, 0x16, 0x10, 0x4f, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xac, 0x8c,
	0x39, 0x88, 0x29, 0x33, 0xc5, 0xc8, 0x89, 0x8b, 0x1b, 0x24, 0x1e, 0x9c, 0x5a, 0x54, 0x96, 0x99,
	0x9c, 0x2a, 0x64, 0xcc, 0xc5, 0x0a, 0x36, 0x57, 0x48, 0x18, 0x6a, 0x04, 0xb2, 0x4b, 0xa4, 0xb0,
	0x08, 0x16, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x45, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0x9b, 0x31, 0xf7, 0xcc, 0x00, 0x00, 0x00,
}
